# Generated by Django 5.1 on 2024-11-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catdry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catdry_id', models.IntegerField()),
                ('catdry_name', models.CharField(max_length=100)),
                ('catdry_desc', models.CharField(max_length=200)),
                ('catdry_price', models.IntegerField()),
                ('catdry_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
