# Generated by Django 5.1 on 2024-11-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Dry Food', 'Dry Food'), ('Wet Food', 'Wet Food'), ('Puppy Food', 'Puppy Food'), ('Grain Food', 'Grain Food'), ('Baked Food', 'Baked Food'), ('Veg Dog Food', 'Veg Dog Food'), ('Premium Food', 'Premium Food')], default='', max_length=50),
        ),
    ]
