# Generated by Django 5.1 on 2024-11-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Dry Food', 'Dry Food'), ('Wet Food', 'Wet Food'), ('Puppy Food', 'Puppy Food'), ('Grain Food', 'Grain Food'), ('Baked Food', 'Baked Food'), ('Veg Dog Food', 'Veg Dog Food'), ('Premium Food', 'Premium Food'), ('Dry Cat Food', 'Dry Cat Food'), ('Wet Cat Food', 'Wet Cat Food'), ('Kitten Food', 'Kitten Food')], default='', max_length=50),
        ),
    ]
