# Generated by Django 5.1 on 2024-11-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_id', models.IntegerField()),
                ('premium_name', models.CharField(max_length=100)),
                ('premium_desc', models.CharField(max_length=200)),
                ('premium_price', models.IntegerField()),
                ('premium_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
