# Generated by Django 5.1 on 2024-11-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_id', models.IntegerField()),
                ('veg_name', models.CharField(max_length=100)),
                ('veg_desc', models.CharField(max_length=200)),
                ('veg_price', models.IntegerField()),
                ('veg_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
