# Generated by Django 5.1 on 2024-11-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain_id', models.IntegerField()),
                ('grain_name', models.CharField(max_length=100)),
                ('grain_desc', models.CharField(max_length=200)),
                ('grain_price', models.IntegerField()),
                ('grain_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
