# Generated by Django 5.1 on 2024-11-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catwet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catwet_id', models.IntegerField()),
                ('catwet_name', models.CharField(max_length=100)),
                ('catwet_desc', models.CharField(max_length=200)),
                ('catwet_price', models.IntegerField()),
                ('catwet_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
