# Generated by Django 5.1.3 on 2025-02-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password1', models.IntegerField()),
                ('Productid', models.IntegerField()),
                ('Orderdate', models.CharField(max_length=100)),
                ('Complaint', models.IntegerField()),
                ('Contact', models.CharField(max_length=100)),
            ],
        ),
    ]
