# Generated by Django 5.1.3 on 2025-02-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='Password1',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='Username',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Complaint',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Orderdate',
            field=models.DateField(),
        ),
    ]
