# Generated by Django 5.1.3 on 2025-02-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_complaint_password1_remove_complaint_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
